ClientBase/Models/Company.cs
using ClientBase.Models.Validation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ClientBase.Models
{
    public class Company : IClientEntity
    {
        public int Id { get; set; }

        [Display(Name = "Идентификационный номер налогоплательщика (ИНН)")]
        [Required(ErrorMessage = "Укажите ИНН")]
        [Range(1000000000, 999999999999, ErrorMessage = "ИНН должен содержать 10 цифр для юридического лица (или 12 для ИП)")]
        [TaxpayerId]
        public long TaxpayerId { get; set; }

        [Display(Name = "Наименование")]
        [Required(ErrorMessage = "Укажите наименование компании")]
        [StringLength(80, MinimumLength = 5, ErrorMessage = "Имя компании должно содержать не менее 5 и не более 80 символов")]
        public string Name { get; set; }

        [Display(Name = "Тип компании")]
        [Required(ErrorMessage = "Необходимо указать тип компании")]
        public bool? IsIndividual { get; set; }

        [Required]
        [Display(Name = "Дата добавления")]
        [DataType(DataType.DateTime)]
        public DateTime CreationDate { get; set; }

        [Display(Name = "Дата обновления")]
        [DataType(DataType.DateTime)]
        public DateTime? UpdateDate { get; set; }

        [Display(Name = "Учредители")]
        [CompanyFounders]
        public ICollection<CompanyFounder> CompanyFounders { get; set; }
    }
}

ClientBase/Models/ViewModels/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientBase.Models.ViewModels
{
    public abstract class ListViewModel
    {
        public string Search { get; set; }

        public PagingInfo PagingInfo { get; set; }
    }
}

ClientBase/Controllers/CompanyController.cs
using ClientBase.Models;
using System;
using System.Linq;

namespace ClientBase.Controllers
{
    public class CompanyController : ClientEntityController<Company>
    {
        #region Messages.

        protected override string CreationSuccessMessage => 
            "Компания успешно добавлена в базу клиентов";

        protected override string UpdateSuccessMessage =>
            "Информация о компании успешно обновлена";

        protected override string UpdateFailedMessage =>
            "Компания с таким ИНН уже зарегистрирована";

        protected override string DeleteSuccessMessage => 
            "Информация о компании удалена";

        protected override string DeleteFailedMessage =>
            "Ошибка при удалении компании из базы данны." +
            "Попробуйте снова, и если проблема повторится, обратитесь к системному администатору";

        #endregion

        protected override Func<Company, object> SelectFromFound => c => new { c.Id, c.Name, c.TaxpayerId };

        protected override Action<Company> EditHook => company =>
        {
            foreach (var companyFounder in company?.CompanyFounders ?? new CompanyFounder[0])
            {
                companyFounder.Company = company;
                companyFounder.CompanyId = company.Id;
            }
        };

        public CompanyController(IEntityRepository<Company> repository)
                    : base(repository)
        {
        }

        protected override IQueryable<Company> GetOrdered()
        {
            return Repository.Entities
                             .OrderByDescending(c => c.UpdateDate ?? c.CreationDate)
                             .ThenBy(c => c.Name);
        }

        protected override IQueryable<Company> GetFiltered(IQueryable<Company> companies, string search)
        {
            return companies.Filter(search);
        }
    }
}

ClientBase/Controllers/FounderController.cs
using ClientBase.Models;
using System;
using System.Linq;

namespace ClientBase.Controllers
{
    public class FounderController : ClientEntityController<Founder>
    {
        #region Messages.

        protected override string CreationSuccessMessage => "Данные об учредителе успешно добавлены";

        protected override string UpdateSuccessMessage => "Данные об учредителе успешно обновлены";

        protected override string UpdateFailedMessage => "Учредитель с таким ИНН уже зарегистрирован";

        protected override string DeleteSuccessMessage => "Данные об учредителе успешно удалены";

        protected override string DeleteFailedMessage => "Ошибка при удалении учредителя из базы данны." +
                               "Попробуйте снова, и если проблема повторится, обратитесь к системному администатору";

        #endregion

        protected override Func<Founder, object> SelectFromFound =>
            f => new { f.Id, Name = f.FullName, f.TaxpayerId };

        public FounderController(IEntityRepository<Founder> repository) : base(repository)
        {
        }

        protected override IQueryable<Founder> GetOrdered()
        {
            return Repository.Entities
                             .OrderByDescending(f => f.UpdateDate ?? f.CreationDate)
                             .ThenBy(f => f.LastName);
        }

        protected override IQueryable<Founder> GetFiltered(IQueryable<Founder> founders, string search)
        {
            return founders.Filter(search);
        }
    }
}

ClientBase/Views/Company/Delete.cshtml
@model Company

@{
    ViewBag.Title = $"Подтверждение удаления компании";
}

<h2>Удаление компании</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<p>Вы действительно хотите удалить компанию <a asp-action="Details" asp-route-id="@Model.Id">«@Model.Name»</a>?</p>
<p>ИНН компании: <strong>@Model.TaxpayerId</strong></p>
<p>Информация об учредителях компании не будет удалена</p>
<div class="text-center">
    <form asp-action="Delete" method="post">
        @Html.HiddenFor(с => с.Id)
        <input class="btn btn-danger" type="submit" value="Удалить">
        <a asp-action="Index" class="btn btn-outline-primary">Отмена</a>
    </form>
</div>

ClientBase/Views/Company/Details.cshtml
@model Company;

@{
    ViewBag.Title = $"{Model.Name}";
}

<h2>Компания «@Model.Name»</h2>

<div class="row mt-3 mb-3">
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary ml-3 mr-3">Редактировать</a>
    <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Удалить</a>
</div>

<dl class="row">
    <dt class="col-sm-2">
        <abbr title="Идентификационный номер налогоплательщика" class="initialism">ИНН</abbr>
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.TaxpayerId)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.CreationDate)
    </dt>
    <dd class="col-sm-10">
        <time datetime="@Model.CreationDate.ToString("o")">@Model.CreationDate.ToString("dd/MM/yyyy в HH:mm")</time>
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.UpdateDate)
    </dt>
    <dd class="col-sm-10">
        @if (Model.UpdateDate == null)
        {
            <span>Данные не редактировались</span>
        }
        else
        {
            <time datetime="@Model.UpdateDate?.ToString("o")">@Model.UpdateDate?.ToString("dd/MM/yyyy в HH:mm")</time>
        }
    </dd>

    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.IsIndividual)
    </dt>
    <dd class="col-sm-10">
        @(Model.IsIndividual == true ? "Индивидуальный предпрениматель" : "Юридическое лицо")
    </dd>

    <dt class="col-sm-2">
        @(Model.IsIndividual == true ? "Учредитель" : "Учредители")
    </dt>
    <dd class="col-sm-10">
        <ul class="list-group list-group-flush">
            @{ var index = 1; }
            @foreach (var company in Model.CompanyFounders)
            {
                <li class="list-group-item">
                    <span class="text-muted">@index </span>
                    <a asp-action="Details" asp-controller="Founder" class="stretched-link" asp-route-id="@company.FounderId">
                        @company.Founder.FullName
                    </a>
                </li>
                index++;
            }
        </ul>
    </dd>
</dl>

ClientBase/Views/Company/Edit.cshtml
@model Company

@{
    ViewBag.Title = Model.Id == 0 ? "Добавление учредителя" : $"{Model.Name} - Редактирование";
}

@using (Html.BeginForm("Edit", "Company", FormMethod.Post, new { id = "founder-edit" }))
{
    @Html.HiddenFor(c => c.Id)
    <div class="form-group">
        <label asp-for="IsIndividual"></label>
        <div><span asp-validation-for="IsIndividual" class="text-danger"></span></div>
        <select asp-for="IsIndividual" class="form-control">
            <option value="">Тип компании</option>
            <option value="true">Индивидуальный предприниматель</option>
            <option value="false">Юридическое лицо</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <div><span asp-validation-for="Name" class="text-danger"></span></div>
        <input asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="TaxpayerId"></label>
        <div><span asp-validation-for="TaxpayerId" class="text-danger"></span></div>
        <input asp-for="TaxpayerId" class="form-control" placeholder="10 цифр (12 для ИП)"
               value="@if (Model.TaxpayerId != 0)
               { @Model.TaxpayerId }" />
    </div>

    <div class="form-group" id="founders">
        <label for="founder-search">Учредители</label>
        <div><span asp-validation-for="CompanyFounders" class="text-danger"></span></div>
        <input type="search"
               name="founder-search"
               id="founder-search"
               autocomplete="off"
               class="form-control"
               placeholder="Поиск учредителя по ФИО и ИНН" />

        <ul class="list-group">
            @foreach (var companyFounder in Model.CompanyFounders?.Where(cf => cf.Founder != null) ?? new CompanyFounder[0])
            {
                    @Html.EditorFor(c => companyFounder);
            }
        </ul>
    </div>

    <div class="validation" asp-validation-summary="ModelOnly"></div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Сохранить">
        <a asp-action="Index" class="btn btn-outline-danger">Отмена</a>
    </div>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/lib/jquery.devbridge-autocomplete/jquery.autocomplete.min.js"></script>
    <script src="~/js/site.js"></script>
}

ClientBase/Views/Company/List.cshtml
@model ListViewModel<Company>
@{
    Layout = "_List";
    ViewBag.Title = "Компании";
}

@foreach (var company in Model.Entities)
{
    <div class="col-lg-6 col-12 mt-2">
        @await Html.PartialAsync("CompanyCard", company)
    </div>
}